# Generated by Django 3.2.25 on 2024-12-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='sroll',
            field=models.IntegerField(),
        ),
    ]
